WITH source AS (
    SELECT * FROM {{ source('raw', 'ENGINE_SENSOR_DATA') }}
)
SELECT
    ENGINE_ID, CYCLE, SETTING1, SETTING2,
    SENSOR_2, SENSOR_3, SENSOR_4, SENSOR_7,
    RUL, FAILURE_IMMINENT, LOAD_TIMESTAMP
FROM source
WHERE SENSOR_2 IS NOT NULL