CREATE DATABASE IF NOT EXISTS AVIONICS_DB;
CREATE SCHEMA IF NOT EXISTS AVIONICS_DB.RAW;
CREATE SCHEMA IF NOT EXISTS AVIONICS_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS AVIONICS_DB.ANALYTICS;
CREATE WAREHOUSE IF NOT EXISTS AVIONICS_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;