USE DATABASE AVIONICS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE ENGINE_SENSOR_DATA (
    ENGINE_ID INTEGER,
    CYCLE INTEGER,
    SETTING1 FLOAT,
    SETTING2 FLOAT,
    SENSOR_2 FLOAT,
    SENSOR_3 FLOAT,
    SENSOR_4 FLOAT,
    SENSOR_7 FLOAT,
    RUL INTEGER,
    FAILURE_IMMINENT INTEGER,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);