WITH staged AS (
    SELECT * FROM {{ ref('stg_engine_sensors') }}
)
SELECT
    ENGINE_ID, CYCLE, RUL, FAILURE_IMMINENT,
    CASE
        WHEN RUL <= 30 THEN 'CRITICAL'
        WHEN RUL <= 60 THEN 'WARNING'
        WHEN RUL <= 100 THEN 'MONITOR'
        ELSE 'HEALTHY'
    END AS MAINTENANCE_RISK_CATEGORY,
    CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM staged